# Generated by Django 4.2.7 on 2024-10-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("code", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
